### PR TITLE
Geocode

### PR DESCRIPTION
**Pull request by akilchomoko**
Added a page for users to see VHS fans near them on a map.
Access from users page.
Additional formating and controls still required.

### CODE REVIEW

**Review by WaynePatrickDalton — APPROVED** [review]
I'll have to take your word that this one works @akilchomoko 😅 No idea what is going on here!

**Comment by akilchomoko** [comment]
You should see: 
image

**Comment by akilchomoko** [comment]
We may have to do a database clean on heroku. For some reason lat/long not being set (db:migrate has been done), when new user created. Works fine locally.

**Comment by akilchomoko** [comment]
> I'll have to take your word that this one works @akilchomoko 😅 No idea what is going on here!

Thanks. Added maps to see users near you. ( /users ).

**Comment by gtm19** [comment]
> We may have to do a database clean on heroku. For some reason lat/long not being set (db:migrate has been done), when new user created. Works fine locally. 

@akilchomoko  My guess is that the service can't distinguish between all the requests it will be getting from the probably thousands of apps on Heroku, and thus we are going over our 1 request per second limit.

I seem to recall you can register and use an API key (still at no cost though) - if so then doing that should fix the problem.

**Pull request merged**
