### PR TITLE
db:seed complete

### PR DESCRIPTION
**Pull request by akilchomoko**
Team,

I've created a db:seed file for Titles and Genres.
If you can review please.

I've done it for year 1982 only, as there are 510 titles in that year. The db:seed file can be adjusted for other years easily if we want to do another year or more. For you to run it, you'll need to add the API key to your ENV file. I'll post this on slack if it's the right place. Need to keep it hidden, as I've put by credit card behind the API. We can call the API 20,000 times in the month. Each movie detail call is an API call. But 20,000 should be enough for us. I've limited the seed fill to create 600 at any one time but it can be changed if needed.

Cheers

### CODE REVIEW

**Review by gtm19 — APPROVED** [review]
@akilchomoko looks good. Make sure you share the API key with us all, or (probably preferably) shoot us a link with where we can get one. Assuming it should go in a `.env` file?

**Comment by akilchomoko** [comment]
I've posted the env on slack.
But hold-off using. Just spotted any error. Our IMDB_ID is an integer whilst the IMDB_ID contains chars. So we need to do a db:migrate. Hold-off for now.

**Comment by akilchomoko** [comment]
> @akilchomoko looks good. Make sure you share the API key with us all, or (probably preferably) shoot us a link with where we can get one. Assuming it should go in a `.env` file?

@gtm19  - Posted on Slack. Yes in your .env

**Comment by akilchomoko** [comment]
Okay, all go. Created db:migrate for IMDB_ID correction in Titles tables.
Just add key (sent via slack) to you .env (all your gemfile are already set up).
Then run db:migrate before running db:seed.

**Comment by akilchomoko** [comment]
@WaynePatrickDalton  To get posters for IMDB_ID, we have a number of options. Either the [Rapid API](https://rapidapi.com/amrelrafie/api/movies-tvshows-data-imdb?endpoint=apiendpoint_a4906f1d-0094-4e55-a22e-8eb53ea0dcee) or http://www.omdbapi.com/. We should discuss if we should possibly cache the images in active_storage, as it otherwise might be really slow (and possibly expensive).

We could also store the main director, actor, rating to in title, if that help the search on the home/index page

**Comment by WaynePatrickDalton** [comment]
Nice one @akilchomoko 👍🏻

**Review by gtm19 — APPROVED** [review]

**Review by WaynePatrickDalton — APPROVED** [review]
We can have a chat about the OMDB vs. Rapid IMBD tonight on a call 👌🏻 - I'll merge this now, as I'm working on search.

**Pull request merged**
